// Shared fixture data used by src/utils/seed.js (full reset) and
// scripts/seed-add-books.js (non-destructive add). Kept separate so the two
// don't drift out of sync with two copies of the same catalog.
//
// These are real, well-known published books. Cover images (in
// src/seed-assets/products/, one per title) were fetched from the Open
// Library Covers API (https://covers.openlibrary.org), a public API
// specifically intended for displaying book covers by ISBN.

const categories = [
  { name: 'Fiction', description: 'Contemporary and classic literary fiction' },
  { name: 'Non-Fiction', description: 'Essays, history, and narrative non-fiction' },
  { name: 'Sci-Fi & Fantasy', description: 'Speculative fiction across galaxies and realms' },
  { name: 'Mystery & Thriller', description: 'Page-turning crime, mystery, and suspense' },
  { name: "Children's", description: 'Picture books and early readers for young minds' },
  { name: 'Biography & Memoir', description: 'Life stories, told first-hand and otherwise' },
  { name: 'Self-Help', description: 'Guides for growth, habits, and wellbeing' },
];

// Raw catalog: genre matches a `categories` name. `category` (the Mongo id)
// is filled in by productsFor() below, once a categoryMap is available.
const BOOKS = [
  {
    genre: 'Fiction',
    name: 'Pride and Prejudice',
    description: "Elizabeth Bennet navigates manners, marriage, and misjudged first impressions in Jane Austen's classic comedy of the English gentry.",
    price: 650,
    stock: 20,
    author: 'Jane Austen',
    publisher: 'Penguin Classics',
    pages: '432 pages',
    isbn: '9780141439518',
    formats: ['Paperback', 'Hardcover'],
    tags: ['Bestseller'],
    cover: 'pride-and-prejudice.jpg',
  },
  {
    genre: 'Fiction',
    name: 'The Great Gatsby',
    description: "Jay Gatsby's obsession with the past collides with the glittering excess of Jazz Age New York.",
    price: 550,
    stock: 18,
    author: 'F. Scott Fitzgerald',
    publisher: 'Scribner',
    pages: '180 pages',
    isbn: '9780743273565',
    formats: ['Paperback', 'Hardcover', 'E-book'],
    tags: ['Bestseller'],
    cover: 'the-great-gatsby.jpg',
  },
  {
    genre: 'Fiction',
    name: '1984',
    description: "Winston Smith quietly rebels against a totalitarian state that watches everything and forgives nothing.",
    price: 600,
    stock: 22,
    author: 'George Orwell',
    publisher: 'Signet Classics',
    pages: '328 pages',
    isbn: '9780451524935',
    formats: ['Paperback', 'E-book'],
    tags: ['Bestseller', 'Award Winner'],
    cover: 'nineteen-eighty-four.jpg',
  },
  {
    genre: 'Non-Fiction',
    name: 'Sapiens: A Brief History of Humankind',
    description: 'A sweeping look at how Homo sapiens came to dominate the planet, from the cognitive revolution to the present day.',
    price: 980,
    stock: 15,
    author: 'Yuval Noah Harari',
    publisher: 'Harper',
    pages: '443 pages',
    isbn: '9780062316097',
    formats: ['Paperback', 'Hardcover', 'E-book'],
    tags: ['Bestseller'],
    cover: 'sapiens.jpg',
  },
  {
    genre: 'Non-Fiction',
    name: 'Educated',
    description: 'A memoir of growing up in a survivalist family in rural Idaho and the education that eventually took her far from home.',
    price: 890,
    stock: 14,
    author: 'Tara Westover',
    publisher: 'Random House',
    pages: '334 pages',
    isbn: '9780399590504',
    formats: ['Paperback', 'Hardcover'],
    tags: ['Award Winner', 'New Arrival'],
    cover: 'educated.jpg',
  },
  {
    genre: 'Non-Fiction',
    name: 'Thinking, Fast and Slow',
    description: 'Nobel laureate Daniel Kahneman maps the two systems that drive the way we think and make decisions.',
    price: 1050,
    stock: 12,
    author: 'Daniel Kahneman',
    publisher: 'Farrar, Straus and Giroux',
    pages: '499 pages',
    isbn: '9780374533557',
    formats: ['Paperback', 'Hardcover'],
    tags: ['Bestseller'],
    cover: 'thinking-fast-and-slow.jpg',
  },
  {
    genre: 'Sci-Fi & Fantasy',
    name: 'Dune',
    description: 'On the desert planet Arrakis, Paul Atreides is thrust into a war over the most valuable resource in the universe.',
    price: 890,
    stock: 16,
    author: 'Frank Herbert',
    publisher: 'Ace Books',
    pages: '412 pages',
    isbn: '9780441013593',
    formats: ['Paperback', 'Hardcover'],
    tags: ['Bestseller', 'Award Winner'],
    cover: 'dune.jpg',
  },
  {
    genre: 'Sci-Fi & Fantasy',
    name: 'The Hobbit',
    description: 'Bilbo Baggins is swept from his comfortable hobbit-hole into an unexpected journey to reclaim a dragon-guarded treasure.',
    price: 750,
    stock: 20,
    author: 'J.R.R. Tolkien',
    publisher: 'Houghton Mifflin',
    pages: '310 pages',
    isbn: '9780547928227',
    formats: ['Paperback', 'Hardcover', 'E-book'],
    tags: ['Bestseller'],
    cover: 'the-hobbit.jpg',
  },
  {
    genre: 'Sci-Fi & Fantasy',
    name: "Ender's Game",
    description: 'A gifted child is trained at Battle School to lead humanity against an insectoid alien threat.',
    price: 680,
    stock: 15,
    author: 'Orson Scott Card',
    publisher: 'Tor Books',
    pages: '324 pages',
    isbn: '9780812550702',
    formats: ['Paperback', 'E-book'],
    tags: ['Award Winner'],
    cover: 'enders-game.jpg',
  },
  {
    genre: 'Mystery & Thriller',
    name: 'The Da Vinci Code',
    description: 'Symbologist Robert Langdon races across Europe chasing a conspiracy hidden in the works of Leonardo da Vinci.',
    price: 720,
    stock: 19,
    author: 'Dan Brown',
    publisher: 'Doubleday',
    pages: '454 pages',
    isbn: '9780307474278',
    formats: ['Paperback', 'Hardcover'],
    tags: ['Bestseller'],
    cover: 'the-da-vinci-code.jpg',
  },
  {
    genre: 'Mystery & Thriller',
    name: 'Gone Girl',
    description: "Nick Dunne's wife disappears on their fifth anniversary, and the marriage he thought he knew unravels in front of the whole country.",
    price: 690,
    stock: 17,
    author: 'Gillian Flynn',
    publisher: 'Crown Publishing',
    pages: '415 pages',
    isbn: '9780307588364',
    formats: ['Paperback', 'E-book'],
    tags: ['Bestseller', 'New Arrival'],
    cover: 'gone-girl.jpg',
  },
  {
    genre: 'Mystery & Thriller',
    name: 'And Then There Were None',
    description: 'Ten strangers are lured to an isolated island, where they are killed off one by one in Agatha Christie’s best-selling mystery.',
    price: 580,
    stock: 21,
    author: 'Agatha Christie',
    publisher: 'William Morrow',
    pages: '264 pages',
    isbn: '9780062073488',
    formats: ['Paperback', 'Hardcover'],
    tags: ['Bestseller'],
    cover: 'and-then-there-were-none.jpg',
  },
  {
    genre: "Children's",
    name: "Charlotte's Web",
    description: 'A pig named Wilbur is saved from the butcher by the words a clever spider spins in her web.',
    price: 520,
    stock: 24,
    author: 'E.B. White',
    publisher: 'Harper & Row',
    pages: '184 pages',
    isbn: '9780064400558',
    formats: ['Paperback', 'Hardcover'],
    tags: ['Staff Pick'],
    cover: 'charlottes-web.jpg',
  },
  {
    genre: "Children's",
    name: 'Matilda',
    description: 'A brilliant little girl with a gift for mischief takes on her dreadful family and a terrifying headmistress.',
    price: 540,
    stock: 22,
    author: 'Roald Dahl',
    publisher: 'Jonathan Cape',
    pages: '240 pages',
    isbn: '9780142410370',
    formats: ['Paperback', 'Hardcover'],
    tags: ['Bestseller'],
    cover: 'matilda.jpg',
  },
  {
    genre: "Children's",
    name: 'The Very Hungry Caterpillar',
    description: 'A tiny, very hungry caterpillar eats his way through the days of the week before a colorful transformation.',
    price: 480,
    stock: 26,
    author: 'Eric Carle',
    publisher: 'World Publishing',
    pages: '26 pages',
    isbn: '9780399226908',
    formats: ['Hardcover'],
    tags: ['Staff Pick', 'Bestseller'],
    cover: 'the-very-hungry-caterpillar.jpg',
  },
  {
    genre: 'Biography & Memoir',
    name: 'Steve Jobs',
    description: "The definitive biography of Apple's co-founder, based on unprecedented access to Jobs and those who knew him.",
    price: 1150,
    stock: 10,
    author: 'Walter Isaacson',
    publisher: 'Simon & Schuster',
    pages: '656 pages',
    isbn: '9781451648539',
    formats: ['Paperback', 'Hardcover', 'E-book'],
    tags: ['Bestseller'],
    cover: 'steve-jobs.jpg',
  },
  {
    genre: 'Biography & Memoir',
    name: 'Becoming',
    description: 'Former First Lady Michelle Obama traces her journey from the South Side of Chicago to the White House.',
    price: 990,
    stock: 13,
    author: 'Michelle Obama',
    publisher: 'Crown Publishing',
    pages: '448 pages',
    isbn: '9781524763138',
    formats: ['Paperback', 'Hardcover'],
    tags: ['Bestseller', 'New Arrival'],
    cover: 'becoming.jpg',
  },
  {
    genre: 'Biography & Memoir',
    name: 'Long Walk to Freedom',
    description: "Nelson Mandela's autobiography, from his rural childhood through 27 years in prison to the presidency of South Africa.",
    price: 950,
    stock: 9,
    author: 'Nelson Mandela',
    publisher: 'Little, Brown and Company',
    pages: '656 pages',
    isbn: '9780316548182',
    formats: ['Paperback', 'Hardcover'],
    tags: ['Award Winner'],
    cover: 'long-walk-to-freedom.jpg',
  },
  {
    genre: 'Self-Help',
    name: 'Atomic Habits',
    description: 'A practical framework for building good habits and breaking bad ones, one tiny change at a time.',
    price: 720,
    stock: 25,
    author: 'James Clear',
    publisher: 'Avery',
    pages: '320 pages',
    isbn: '9780735211292',
    formats: ['Paperback', 'Hardcover', 'E-book'],
    tags: ['Bestseller'],
    cover: 'atomic-habits.jpg',
  },
  {
    genre: 'Self-Help',
    name: 'The 7 Habits of Highly Effective People',
    description: 'A principle-centered approach to personal and professional effectiveness that has shaped a generation of readers.',
    price: 690,
    stock: 18,
    author: 'Stephen R. Covey',
    publisher: 'Free Press',
    pages: '381 pages',
    isbn: '9780743269513',
    formats: ['Paperback', 'Hardcover'],
    tags: ['Bestseller'],
    cover: 'the-7-habits.jpg',
  },
  {
    genre: 'Self-Help',
    name: 'How to Win Friends and Influence People',
    description: 'Dale Carnegie’s enduring guide to building relationships, winning people over, and communicating with confidence.',
    price: 560,
    stock: 20,
    author: 'Dale Carnegie',
    publisher: 'Simon & Schuster',
    pages: '291 pages',
    isbn: '9780671027032',
    formats: ['Paperback'],
    tags: ['Bestseller', 'New Arrival'],
    cover: 'how-to-win-friends.jpg',
  },
];

function productsFor(categoryMap) {
  return BOOKS.map(({ genre, cover, ...book }) => ({
    ...book,
    category: categoryMap[genre],
    images: [`/uploads/products/${cover}`],
  }));
}

module.exports = { categories, BOOKS, productsFor };
